#!/bin/bash
#based on 'crep' script from Campbell Barton

OUT="/tmp/mktmp"
git branch --list | sort > $OUT

# Print text with line numbers
sed = $OUT | sed 'N;s/\n/ /'

echo -n "enter a number to edit > "
read LINE

if [ "$LINE" -eq "" ] ; then
    echo "nothing selected... exiting."
    return 0
fi

EDIT=$(awk "NR==$LINE {gsub(/^[ \t]+|[ \t]+$/, \"\"); print; exit}" "$OUT")

rm $OUT

# Now change the branch
git checkout $EDIT

